types/round_info.go
Relates to: 
*Add round-info data struct.*
=> feat($Add): Add round-info data struct.

storage/caches.go
Relates to: 
*Add caches and re-fmt project.*
=> feat($Add): Add caches and refmt project.

cmd/paradigm/main.go, core/accretion/accretion.go, core/node.go, core/sequentia/sequentia.go, network/peer/peer.go, version/version.go
Relates to: 
*Add command,core,version package.*
=> feat($Add): Add command,core,version package.

cmd/paradigm/main.go, network/peer/peer.go, network/tcp/net_transport.go, network/tcp/tcp_stream_layer.go, network/transport.go, storage/badger_store.go, storage/caches.go, storage/memory_store.go, storage/store.go, types/comet.go, version/version.go
Add badger store implement of store interface.
Relates to: 
*Add badger(K-V) store implement of store interface.*
=> feat($Add): Add badger store implement of store interface.

accounts/accounts.go, accounts/url.go
Relates to: 
*Paradigm Accounts interface.*
=> Paradigm Accounts interface.

accounts/accounts.go, accounts/errors.go, accounts/hd.go, accounts/manager.go, accounts/url.go
Relates to: 
*manager, an overarching account manager.*
=> manager, an overarching account manager 

.gitignore, common/log/logger.go, common/timer/control_timer.go, core/config.go, core/core.go, core/node.go, core/node_state.go, core/sequentia/peer_selector.go, network/transport.go, proxy/proxy.go
Relates to: 
*Add node config, modify gitignore file.*
=> feat($Add): Add node config, modify gitignore file.

core/config.go, core/node.go, network/peer/peer.go, network/tcp/net_transport.go, proxy/inmem_proxy.go
Relates to: 
*Add in memory proxy for test and local use.
Add default config, tcp transport implement, add proxy.*
=> Add default config, tcp transport implement, add proxy.

README.md, makefile, proxy/inmem_proxy.go
Relates to: 
*Add makefile for build, add in memory proxy.*
=> Add makefile for build, add in memory proxy.

accounts/keystore/key.go, accounts/keystore/keystore.go, accounts/keystore/keystore_passphrase.go, accounts/keystore/presale.go
Relates to: 
*Add keystore,  an implementation of backend.*
=> Add keystore,  an implementation of backend

accounts/keystore/account_cache.go, accounts/keystore/key.go, accounts/keystore/keystore.go, accounts/keystore/keystore_passphrase.go, accounts/keystore/presale.go, accounts/keystore/watch.go
Relates to: 
*add 6 files, functions refined.*
=> add 6 files, functions refined

cmd/paradigm/main.go, common/rolling_index.go, common/rolling_index_map.go, core/core.go, core/node.go, core/sequentia/sequentia.go, network/tcp/net_transport.go, storage/badger_store.go, storage/caches.go, types/comet.go, types/comet_test.go
Relates to: 
* Fix comet transfer with json format cause signature error.
Fix node rpc types error.
Add some log in sequentia and node for debug.
Fix comet transfer with json format cause signature error.*
=>  Fix comet transfer with json format cause signature error.

.gitignore, cmd/paradigm/main.go, common/crypto/pem_key.go, common/file/chown.go, common/file/chown_linux.go, common/log/logger.go, common/log/logger_test.go, common/log/rotate.go, types/comet_test.go
Relates to: 
*Add rotate logger for file rolling and compress.*
=> Add rotate logger for file rolling and compress.

accounts/errors.go, accounts/keystore/account_cache.go, accounts/keystore/file_cache.go, accounts/keystore/key.go, accounts/keystore/keystore.go, accounts/keystore/keystore_passphrase.go, accounts/keystore/keystore_wallet.go, accounts/keystore/presale.go, accounts/keystore/watch.go
Relates to: 
*add 9 files,new functions.*
=> add 9 files,new functions

cmd/paradigm/main.go, storage/badger_store.go, types/comet.go
Relates to: 
*Fix main and store logger.remove useless output.*
=> fix($Log): Fix main and store logger.remove useless output.

accounts/accounts.go, accounts/keystore/account_cache.go
Relates to: 
*add 1  note and noted Transaction to be defined.*
=> add 1  note and noted Transaction to be defined

common/rlp/decode.go, common/rlp/decode_tail_test.go, common/rlp/decode_test.go, common/rlp/encode.go, common/rlp/encode_test.go, common/rlp/encoder_example_test.go, common/rlp/raw.go, common/rlp/raw_test.go, common/rlp/typecache.go, storage/badger_store.go, storage/store.go, tire/tire.go, trie/encoding.go, trie/node.go, trie/trie.go
Relates to: 
*Add and implement storage functions that trie needed.*
=> feat($Add): Add and implement storage functions that trie needed.

common/bytes.go, common/crypto/crypto.go, common/crypto/secp256k1/curve.go, common/crypto/signature_cgo.go, common/crypto/utils.go, common/hexutil/hexutil.go, common/hexutil/hexutil_test.go, common/hexutil/json.go, common/hexutil/json_example_test.go, common/hexutil/json_test.go, common/rlp/decode.go, common/rlp/decode_tail_test.go, common/rlp/decode_test.go, common/rlp/encode.go, common/rlp/encode_test.go, common/rlp/encoder_example_test.go, common/rlp/raw.go, common/rlp/raw_test.go, common/rlp/typecache.go, common/types.go, storage/badger_store.go, storage/store.go, tire/tire.go, trie/encoding.go, trie/errors.go, trie/hasher.go, trie/iterator.go, trie/node.go, trie/trie.go
Relates to: 
*Add and implement storage functions that trie needed..*
=> Add and implement storage functions that trie needed.

.idea/vcs.xml, accounts/accounts.go, accounts/keystore/account_cache.go, accounts/keystore/file_cache.go, accounts/keystore/key.go, accounts/keystore/keystore.go, accounts/keystore/keystore_passphrase.go, accounts/keystore/keystore_wallet.go, accounts/manager.go, common/crypto/crypto.go, common/crypto/pem_key.go, common/crypto/signature_cgo.go, common/crypto/utils.go, common/event/feed.go, common/event/subscription.go, common/log/handler.go, common/log/handler_go14.go, common/log/logger.go, common/log/root.go, common/types.go, common/types/transaction.go, common/types/transaction_signing.go
Relates to: 
*Solve Merge conflict.*
=> Solve Merge conflict.

accounts/keystore/keystore.go, common/crypto/signature.go, common/crypto/utils.go, glide.yaml, types/block.go, types/comet.go
Relates to: 
*Fix signature with ECDSA, add btcec deps in glide.yaml.*
=> Fix signature with ECDSA, add btcec deps in glide.yaml.

cmd/paradigm/main.go, core/config.go, network/http/base/rpc/rpc.go, network/http/error/error.go, network/http/jsonrpc/rpc_server.go, network/http/service/service.go
Relates to: 
*feat($Add): Add StartRPCServer function.*
=> feat($Add): Add StartRPCServer function

common/size.go, types/bloom9.go, types/gen_tx_json.go, types/receipt.go, types/transaction.go
Relates to: 
*Add transaction,receipt,bloom types.*
=> feat($Add): Add transaction,receipt,bloom types.

network/http/base/rpc/rpc.go, network/http/jsonrpc/rpc_server.go
Relates to: 
*perf($Delete): logger ajustement.*
=> perf($Delete): logger ajustement

.gitignore, cmd/paradigm/main.go, common/crypto/crypto.go, common/math/big.go, common/types.go, config/config.go, core/node.go, glide.yaml, network/http/jsonrpc/rpc_server.go, network/http/service/service.go, proxy/errors.go, proxy/inmem_proxy.go, proxy/proxy_handlers.go, proxy/proxy_processor.go, proxy/proxy_service.go, proxy/proxy_state.go, proxy/proxy_was_state.go, state/statedb.go, types/signer.go
Relates to: 
*Add state execute logic in proxy layer.
Fix reboot node state init error.*
=> Add state execute logic in proxy layer.

proxy/inmem_proxy.go, proxy/proxy_handlers.go, proxy/proxy_state.go
Relates to: 
*Add Tps printer for proxy.*
=> feat($Add): Add Tps printer for proxy.

common/common.go, common/inventory.go, common/safeMath.go, common/serialization/serialize.go, common/serialization/serialize_test.go, common/uint256.go, common/zero_copy_sink.go, common/zero_copy_source.go, config/config.go, errors/callstack.go, errors/errcode.go, errors/errors.go, errors/onterror.go
Relates to: 
*feat($Add): Add errors and common files for p2pserver module.*
=>  feat($Add): Add errors and common files for p2pserver module.

cmd/paradigm/main.go, core/core.go, core/node.go, core/sequentia/sequentia.go, proxy/inmem_proxy.go, proxy/mem_pool.go, proxy/proxy_handlers.go, proxy/proxy_processor.go, proxy/proxy_service.go, proxy/proxy_state.go, state/managed_state.go
Relates to: 
*Fix logger level to debug, add managed state for nonce seq.*
=> fix($Fix): Fix logger level to debug, add managed state for nonce seq.

accounts/keystore/account_cache.go, accounts/keystore/account_cache_test.go, accounts/keystore/file_cache.go, proxy/proxy_processor.go, proxy/proxy_state.go
Relates to: 
*fix($Fix): update some relative package.*
=> fix($Fix): update some relative package
